### ISSUE TITLE
Es Diana Alejandra #23 y mando mi diseño así poque no me deja dar pull request.

### ISSUE THREAD

**Issue by DianaAlejandra2007** [pomaray/5to_23-24_sistema-gestor-calificacion#26]
![diseño proyecto](https://github.com/pomaray/5to_23-24_sistema-gestor-calificacion/assets/161880345/8c88683f-6359-43a1-88b4-acf030414a97)

**Comment by eliasdanielr** [comment]
Ya puedes subir tu maqueta @DianaAlejandra2007

**Comment by eliasdanielr** [comment]
Cerrada por resolucion
